### ISSUE TITLE
How to import progress-ring component to react project?

### ISSUE THREAD

**Issue by elgeneee** [taisuke-j/progress-ring-component#19]

**Comment by taisuke-j** [comment]
Please check the instructions below. If you have any issues, do let me know.

https://github.com/taisuke-j/progress-ring-component#react

**Comment by taisuke-j** [comment]
@elgeneee I updated the section and hopefully it helps!
https://github.com/taisuke-j/progress-ring-component#react

**Comment by taisuke-j** [comment]
Now we have React version of the component
https://www.npmjs.com/package/progress-ring-component-react
